In [1]:
import torch
import torch.nn as nn
import torch
from torch.utils.data import Dataset
from torch.utils.data.dataloader import DataLoader
from utils import set_seed
set_seed(3407)
import numpy as np
import pylab as plt
import pandas as pd

In [9]:

class TabularRegressionData(Dataset):
    """ 
    Simple tabular data with 5 numerical features and 1 numerical response. 
    """

    def __init__(self, split, dimensions = 5):
        assert split in {'train', 'test'}
        self.split = split
        self.dimensions = dimensions
        
    def __len__(self):
        return 10000 # ...
    
    def __getitem__(self, idx):
        x = torch.randn(5)
        y = x[0] + (2 * x[2] * x[3]) - 3 * (x[4]**2)
        x, y
        return x, y


In [31]:
train_dataset = TabularRegressionData('train')

In [32]:
len(train_dataset)

10000

In [20]:
a[0:2]

[tensor([-0.0572, -0.6023, -0.7835, -1.5824,  0.3470]),
 tensor([-0.8811,  0.3876, -0.8624,  0.1805,  2.6876])]

In [19]:
a[9999:10003]

[tensor([ 0.4732, -0.4179, -0.6070,  0.6187,  1.1693]),
 tensor([-0.3129,  0.7711,  2.0007,  0.8142, -0.3442]),
 tensor([ 0.0868, -0.2618, -0.4838, -0.3490, -1.2614]),
 tensor([ 0.1804,  0.4496,  1.9308, -0.0606, -0.0668])]

In [56]:
a = []
b = []
for (x,y) in train_dataset: 
    a.append(np.array(x))
    b.append(y.item())
    if len(a) >= 10000: 
        break
df = pd.DataFrame(a)
df.columns = ['x0','x1','x2','x3','x4']
df['y'] = b

In [58]:
df.head()

x0        x1        x2        x3        x4         y
0  1.666430  0.595244 -0.161818 -0.467741 -0.235234  1.651802
1 -0.000772  1.050795  0.863816  0.318068 -0.040953  0.543701
2 -2.715449 -0.828094  1.756049 -0.687920 -0.415605 -5.649674
3 -0.405523 -0.009845 -2.316641  0.163378 -1.674237 -9.571711
4 -1.646876  0.072499  0.015248 -0.978387 -1.183165 -5.876352

In [59]:
df.to_csv("/home/suhas/research/dl/training_data.txt", index = False)

In [12]:
train_dataset.to_csv("/home/suhas/research/dl/training.txt")

AttributeError: 'TabularRegressionData' object has no attribute 'to_csv'

In [17]:
import torch
from torch.utils.data import Dataset
from torch.utils.data.dataloader import DataLoader
from utils import set_seed
import sys
set_seed(3407)
import pylab as plt
import pandas as pd
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter()

2024-04-30 15:14:26.613696: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-30 15:14:26.775150: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-04-30 15:14:26.775173: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-04-30 15:14:27.413704: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2024-

In [20]:
import pickle

class TabularRegressionData(Dataset):
    """ 
    Simple tabular data with 5 numerical features and 1 numerical response. 
    """

    def __init__(self, split, dimensions = 5):
        assert split in {'train', 'test'}
        self.split = split
        self.dimensions = dimensions
        
    def __len__(self):
        return 10000 # ...
    
    def __getitem__(self, idx):
        x = torch.randn(5)
        y = -3.15 + x[0] + (2 * x[2] * x[3]) - 3 * (x[4]**3)
        w = torch.rand(1)
        return x, y, w


In [22]:
# print an example instance of the dataset
train_dataset = TabularRegressionData('train')
test_dataset = TabularRegressionData('test')
x, y, w = train_dataset[0]
print(x, y, w)


tensor([ 0.1052, -1.2552, -0.1762,  0.5020, -0.2873]) tensor(-3.1506) tensor([0.6665])


In [25]:
x = torch.rand(size = (2, 3))

In [26]:
x

tensor([[0.2209, 0.0954, 0.9996],
        [0.1764, 0.3382, 0.0200]])

In [27]:
x.shape

torch.Size([2, 3])

In [29]:
x.size()

torch.Size([2, 3])

In [31]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.]])